version: "3.8"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    environment:
      DATABASE_URL: postgresql://postgres:secret@db:5432/postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    depends_on:
      - db
    ports:
      - "8000:8000"

volumes:
  postgres_data:
